### ISSUE TITLE
Background isn't fixed

### ISSUE THREAD

**Issue by SimulatedGREG** [jackel27/jackel-todo-app#1]
When there are enough tasks to enable scrolling, the background image isn't fixed and scrolls with the tasks.

![image](https://cloud.githubusercontent.com/assets/8327811/26030111/99335ffe-380e-11e7-900e-5bd1e20c5814.png)

**Comment by jackel27** [comment]
@SimulatedGREG  Thanks for the catch! Resolved with a fixed background. 👍
